Resolved issue where a beta python version in the python_version marker would cause an error.
